In [ ]:
import pandas as pd
import numpy as np

In [ ]:
# Task 1.

df = pd.read_csv("//content//ipl_match_result.txt")

In [ ]:
df

,Match_ID,Season,Date,Venue,Team1,Team2,Toss_Winner,Toss_Decision,Winner,Result,Win_By_Runs,Win_By_Wickets,Player_of_Match
0,1,2024,2024-03-22,M Chinnaswamy Stadium,RCB,CSK,CSK,Field,CSK,Normal,0,6,Mustafizur Rahman
1,2,2024,2024-03-23,IS Bindra Stadium,PBKS,DC,PBKS,Bat,PBKS,Normal,4,0,Sam Curran
2,3,2024,2024-03-24,Eden Gardens,KKR,SRH,SRH,Field,KKR,Normal,4,0,Andre Russell
3,4,2024,2024-03-24,Rajasthan Stadium,RR,LSG,LSG,Field,RR,Normal,20,0,Sanju Samson
4,5,2024,2024-03-25,Narendra Modi Stadium,GT,MI,GT,Bat,GT,Normal,6,0,Shubman Gill
5,6,2024,2024-03-26,MA Chidambaram Stadium,CSK,GT,GT,Field,CSK,Normal,63,0,Rachin Ravindra
6,7,2024,2024-03-27,Hyderabad Stadium,SRH,MI,SRH,Bat,SRH,Normal,31,0,Abhishek Sharma
7,8,2024,2024-03-28,M Chinnaswamy Stadium,RCB,PBKS,PBKS,Field,RCB,Normal,4,0,Virat Kohli
8,9,2024,2024-03-29,Ekana Stadium,LSG,PBKS,LSG,Bat,LSG,Normal,21,0,Mayank Yadav
9,10,2024,2024-03-30,MA Chidambaram Stadium,CSK,DC,DC,Field,DC,Normal,20,0,Khaleel Ahmed
10,11,2024,2024-03-31,Narendra Modi Stadium,GT,SRH,SRH,Field,GT,Normal,7,0,Mohit Sharma
11,12,2024,2024-04-01,Wankhede Stadium,MI,RR,RR,Field,RR,Normal,0,6,Yashasvi Jaiswal
12,13,2024,2024-04-02,Chinnaswamy Stadium,RCB,LSG,RCB,Bat,LSG,Normal,0,28,Mayank Yadav
13,14,2024,2024-04-03,Arun Jaitley Stadium,DC,KKR,KKR,Field,KKR,Normal,106,0,Sunil Narine
14,15,2024,2024-04-04,Hyderabad Stadium,SRH,CSK,SRH,Bat,SRH,Normal,6,0,Abhishek Sharma
15,16,2024,2024-04-05,Wankhede Stadium,MI,DC,MI,Bat,MI,Normal,29,0,Rohit Sharma
16,17,2024,2024-04-06,Ahmedabad Stadium,GT,PBKS,PBKS,Field,PBKS,Normal,0,3,Shashank Singh
17,18,2024,2024-04-07,Jaipur Stadium,RR,RCB,RR,Field,RR,Normal,6,0,Jos Buttler
18,19,2024,2024-04-08,MA Chidambaram Stadium,CSK,KKR,KKR,Bat,CSK,Normal,7,0,Ravindra Jadeja
19,20,2024,2024-04-09,Arun Jaitley Stadium,DC,LSG,LSG,Field,LSG,Normal,0,6,Marcus Stoinis
20,21,2024,2024-04-10,Hyderabad Stadium,SRH,GT,GT,Field,GT,Normal,7,0,Shubman Gill
21,22,2024,2024-04-11,Wankhede Stadium,MI,RCB,RCB,Field,MI,Normal,0,7,Suryakumar Yadav
22,23,2024,2024-04-12,Ekana Stadium,LSG,DC,DC,Field,DC,Normal,6,0,Kuldeep Yadav
23,24,2024,2024-04-13,Punjab Stadium,PBKS,RR,RR,Field,RR,Normal,3,0,Shimron Hetmyer
24,25,2024,2024-04-14,Chinnaswamy Stadium,RCB,SRH,SRH,Bat,SRH,Normal,25,0,Travis Head
25,26,2024,2024-04-15,Hyderabad Stadium,SRH,MI,MI,Field,SRH,Normal,31,0,Travis Head
26,27,2024,2024-04-16,Ahmedabad Stadium,GT,RR,RR,Field,GT,Normal,3,0,Rashid Khan
27,28,2024,2024-04-17,Arun Jaitley Stadium,DC,GT,DC,Bat,DC,Normal,6,0,Rishabh Pant
28,29,2024,2024-04-18,Mullanpur Stadium,PBKS,MI,MI,Field,MI,Normal,0,9,Jasprit Bumrah
29,30,2024,2024-04-19,Ekana Stadium,LSG,CSK,CSK,Field,LSG,Normal,8,0,KL Rahul
30,31,2024,2024-04-20,Arun Jaitley Stadium,DC,SRH,SRH,Bat,SRH,Normal,67,0,Travis Head
31,32,2024,2024-04-21,Eden Gardens,KKR,RCB,RCB,Field,KKR,Normal,1,0,Will Jacks
32,33,2024,2024-04-22,Rajasthan Stadium,RR,MI,MI,Field,RR,Normal,9,0,Yashasvi Jaiswal
33,34,2024,2024-04-23,Chandigarh Stadium,PBKS,GT,GT,Field,GT,Normal,3,0,Prabhsimran Singh
34,35,2024,2024-04-24,MA Chidambaram Stadium,CSK,LSG,LSG,Field,LSG,Normal,0,8,Marcus Stoinis
35,36,2024,2024-04-25,Hyderabad Stadium,SRH,RCB,RCB,Field,RCB,Normal,35,0,Rajath Patidar
36,37,2024,2024-04-26,Eden Gardens,KKR,PBKS,PBKS,Field,PBKS,Normal,8,0,Jonny Bairstow
37,38,2024,2024-04-27,Delhi Stadium,DC,MI,MI,Field,DC,Normal,10,0,Jake Fraser-McGurk
38,39,2024,2024-04-28,Ahmedabad Stadium,GT,RCB,RCB,Field,RCB,Normal,9,0,Will Jacks
39,40,2024,2024-04-29,Eden Gardens,KKR,DC,DC,Field,KKR,Normal,7,0,Varun Chakravarthy
40,41,2024,2024-04-30,LSG Stadium,LSG,MI,MI,Field,LSG,Normal,4,0,Marcus Stoinis
41,42,2024,2024-05-01,Chepauk Stadium,CSK,PBKS,PBKS,Field,PBKS,Normal,7,0,Harshal Patel
42,43,2024,2024-05-02,Hyderabad Stadium,SRH,RR,RR,Field,SRH,Normal,1,0,Bhuvneshwar Kumar
43,44,2024,2024-05-03,Wankhede Stadium,MI,KKR,KKR,Field,KKR,Normal,24,0,Venkatesh Iyer
44,45,2024,2024-05-04,Chinnaswamy Stadium,RCB,GT,GT,Field,RCB,Normal,4,0,Faf du Plessis
45,46,2024,2024-05-05,Delhi Stadium,DC,RR,RR,Field,DC,Normal,20,0,Abishek Porel
46,47,2024,2024-05-06,Ahmedabad Stadium,GT,CSK,CSK,Field,GT,Normal,35,0,Mohit Sharma
47,48,2024,2024-05-07,Hyderabad Stadium,SRH,LSG,LSG,Field,SRH,Normal,10,0,Pat Cummins
48,49,2024,2024-05-08,Chinnaswamy Stadium,RCB,PBKS,PBKS,Field,RCB,Normal,0,4,Virat Kohli
49,50,2024,2024-05-09,Eden Gardens,KKR,MI,MI,Field,KKR,Normal,18,0,Sunil Narine

In [ ]:
# df.head(6)

In [ ]:
df.isna().sum()

Match_ID             0
Season               0
Date                 0
Venue                0
Team1                0
Team2                0
Toss_Winner          0
Toss_Decision        0
Winner               0
Result               0
Win_By_Runs          0
Win_By_Wickets       0
Player_of_Match      0
match_margin_type    0
dtype: int64

In [ ]:
ipl_df =df
conditions =[ipl_df["Win_By_Runs"] > 0, ipl_df["Win_By_Wickets"] > 0]

choices = ["Runs","Wickets"]

ipl_df["match_margin_type"] = np.select(conditions,choices,default="Tie/No Result")

ipl_df.head()

,Match_ID,Season,Date,Venue,Team1,Team2,Toss_Winner,Toss_Decision,Winner,Result,Win_By_Runs,Win_By_Wickets,Player_of_Match,match_margin_type
0,1,2024,2024-03-22,M Chinnaswamy Stadium,RCB,CSK,CSK,Field,CSK,Normal,0,6,Mustafizur Rahman,Wickets
1,2,2024,2024-03-23,IS Bindra Stadium,PBKS,DC,PBKS,Bat,PBKS,Normal,4,0,Sam Curran,Runs
2,3,2024,2024-03-24,Eden Gardens,KKR,SRH,SRH,Field,KKR,Normal,4,0,Andre Russell,Runs
3,4,2024,2024-03-24,Rajasthan Stadium,RR,LSG,LSG,Field,RR,Normal,20,0,Sanju Samson,Runs
4,5,2024,2024-03-25,Narendra Modi Stadium,GT,MI,GT,Bat,GT,Normal,6,0,Shubman Gill,Runs

In [ ]:
team_city = pd.DataFrame({"Team": ["GT", "RCB", "MI", "CSK", "KKR", "DC", "SRH", "RR"],
                          "Home_City": ["Ahmedabad","Bengaluru","Mumbai","Chennai","Kolkata","Delhi","Hyderabad", "Jaipur"]})

print(team_city)

#Team 1
ipl_df = ipl_df.merge(team_city,left_on="Team1",right_on="Team",how="left")

ipl_df = ipl_df.rename(columns={"Home_City": "Team1_Home_City"})

ipl_df = ipl_df.drop(columns=["Team"])

#Team 2
ipl_df = ipl_df.merge(team_city,
    left_on="Team2",
    right_on="Team",
    how="left")

ipl_df = ipl_df.rename(columns={"Home_City": "Team2_Home_City"})

ipl_df = ipl_df.drop(columns=["Team"])

  Team  Home_City
0   GT  Ahmedabad
1  RCB  Bengaluru
2   MI     Mumbai
3  CSK    Chennai
4  KKR    Kolkata
5   DC      Delhi
6  SRH  Hyderabad
7   RR     Jaipur

In [ ]:
print(ipl_df[["Team1", "Team1_Home_City","Team2","Team2_Home_City"]].head(10))

  Team1 Team1_Home_City Team1_Home_City Team1_Home_City Team1_Home_City  \
0   RCB       Bengaluru       Bengaluru       Bengaluru       Bengaluru
1  PBKS             NaN             NaN             NaN             NaN
2   KKR         Kolkata         Kolkata         Kolkata         Kolkata
3    RR          Jaipur          Jaipur          Jaipur          Jaipur
4    GT       Ahmedabad       Ahmedabad       Ahmedabad       Ahmedabad
5   CSK         Chennai         Chennai         Chennai         Chennai
6   SRH       Hyderabad       Hyderabad       Hyderabad       Hyderabad
7   RCB       Bengaluru       Bengaluru       Bengaluru       Bengaluru
8   LSG             NaN             NaN             NaN             NaN
9   CSK         Chennai         Chennai         Chennai         Chennai

  Team1_Home_City Team1_Home_City Team1_Home_City Team1_Home_City Team2  \
0       Bengaluru       Bengaluru       Bengaluru       Bengaluru   CSK
1             NaN             NaN             NaN             NaN    DC
2         Kolkata         Kolkata         Kolkata         Kolkata   SRH
3          Jaipur          Jaipur          Jaipur          Jaipur   LSG
4       Ahmedabad       Ahmedabad       Ahmedabad       Ahmedabad    MI
5         Chennai         Chennai         Chennai         Chennai    GT
6       Hyderabad       Hyderabad       Hyderabad       Hyderabad    MI
7       Bengaluru       Bengaluru       Bengaluru       Bengaluru  PBKS
8             NaN             NaN             NaN             NaN  PBKS
9         Chennai         Chennai         Chennai         Chennai    DC

  Team2_Home_City Team2_Home_City Team2_Home_City Team2_Home_City  \
0         Chennai         Chennai         Chennai         Chennai
1           Delhi           Delhi           Delhi           Delhi
2       Hyderabad       Hyderabad       Hyderabad       Hyderabad
3             NaN             NaN             NaN             NaN
4          Mumbai          Mumbai          Mumbai          Mumbai
5       Ahmedabad       Ahmedabad       Ahmedabad       Ahmedabad
6          Mumbai          Mumbai          Mumbai          Mumbai
7             NaN             NaN             NaN             NaN
8             NaN             NaN             NaN             NaN
9           Delhi           Delhi           Delhi           Delhi

  Team2_Home_City
0         Chennai
1           Delhi
2       Hyderabad
3             NaN
4          Mumbai
5       Ahmedabad
6          Mumbai
7             NaN
8             NaN
9           Delhi

In [ ]:
# Create pivot table: total wins by each team per season

wins_pivot = pd.pivot_table(ipl_df,index="Winner",columns="Season",values="Match_ID",aggfunc="count",fill_value=0)

print(wins_pivot)

Season  2024
Winner
CSK        3
DC         5
GT         6
KKR        6
LSG        6
MI         3
PBKS       4
RCB        5
RR         5
SRH        7

In [ ]:
# Convert pivot table into a normal DataFrame

top_3 = (wins_pivot.reset_index().melt(id_vars="Winner", var_name="Season", value_name="Wins")
          .sort_values("Wins", ascending=False).head(3))

print(top_3)

  Winner Season  Wins
9    SRH   2024     7
2     GT   2024     6
4    LSG   2024     6